from typing_extensions import TypedDict


class AriaProps(TypedDict, total=False):
    aria_active_descendant: str
    aria_atomic: str
    aria_auto_complete: str
    aria_busy: str
    aria_checked: str
    aria_col_count: str
    aria_col_index: str
    aria_col_span: str
    aria_controls: str
    aria_current: str
    aria_described_by: str
    aria_details: str
    aria_disabled: str
    aria_drop_effect: str
    aria_error_message: str
    aria_expanded: str
    aria_flow_to: str
    aria_grabbed: str
    aria_has_popup: str
    aria_hidden: str
    aria_invalid: str
    aria_key_shortcuts: str
    aria_label: str
    aria_labelled_by: str
    aria_level: str
    aria_live: str
    aria_modal: str
    aria_multiline: str
    aria_multi_selectable: str
    aria_orientation: str
    aria_owns: str
    aria_placeholder: str
    aria_pos_inset: str
    aria_pressed: str
    aria_readonly: str
    aria_relevant: str
    aria_required: str
    aria_role_description: str
    aria_row_count: str
    aria_row_index: str
    aria_row_span: str
    aria_selected: str
    aria_set_size: str
    aria_sort: str
    aria_value_max: str
    aria_value_min: str
    aria_value_now: str
    aria_value_text: str
