import os

from .version import version as __version__

__all__ = ["__version__"]

if not os.environ.get("SEAMLESS_VERSION_ONLY", False):
    from ._init import *

    __all__ = [
        "Component",
        "A",
        "Abbr",
        "Address",
        "Area",
        "Article",
        "Aside",
        "B",
        "Base",
        "BlockQuote",
        "Body",
        "Br",
        "Button",
        "Canvas",
        "Cite",
        "Code",
        "Col",
        "Div",
        "Em",
        "Embed",
        "Footer",
        "Form",
        "Fragment",
        "H1",
        "H2",
        "H3",
        "H4",
        "H5",
        "H6",
        "Head",
        "Header",
        "Hr",
        "Html",
        "I",
        "Img",
        "Input",
        "Label",
        "Li",
        "Link",
        "Main",
        "Meta",
        "Nav",
        "Ol",
        "Option",
        "P",
        "Param",
        "Pre",
        "Script",
        "Section",
        "Select",
        "Small",
        "Source",
        "Span",
        "Strong",
        "Style",
        "Sub",
        "Sup",
        "Table",
        "TBody",
        "Td",
        "TextArea",
        "Th",
        "THead",
        "Time",
        "Title",
        "Tr",
        "Track",
        "U",
        "Ul",
        "Wbr",
        "Context",
        "JS",
        "render",
        "__version__",
    ]
