SEAMLESS_ELEMENT_ATTRIBUTE = "seamless:element"
SEAMLESS_INIT_ATTRIBUTE = "seamless:init"

DISABLE_GLOBAL_CONTEXT_ENV = "SEAMLESS_DISABLE_GLOBAL_CONTEXT"
DISABLE_VALIDATION_ENV = "SEAMLESS_DISABLE_VALIDATION"

UNSAFE_GLOBAL_EVENT_ATTRIBUTE = "seamless:unsafe-global-event"