SEAMLESS_ELEMENT_ATTRIBUTE = "seamless:element"
SEAMLESS_INIT_ATTRIBUTE = "seamless:init"
SEAMLESS_INIT_ASYNC_ATTRIBUTE = "seamless:async"

DISABLE_GLOBAL_CONTEXT_ENV = "SEAMLESS_DISABLE_GLOBAL_CONTEXT"